name: Feature request
description: Suggest an feature / idea for this project
title: "[Feature Request / Suggestion]: "
labels: ["enhancement"]
body:
- type: checkboxes
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: **Black cat**
